var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// server.ts
var import_express = __toESM(require("express"), 1);
var import_path = __toESM(require("path"), 1);
var import_url = require("url");
var import_genai = require("@google/genai");
var import_dotenv = __toESM(require("dotenv"), 1);
var import_meta = {};
import_dotenv.default.config();
var __filename = (0, import_url.fileURLToPath)(import_meta.url);
var __dirname = import_path.default.dirname(__filename);
var app = (0, import_express.default)();
var PORT = 3e3;
app.use(import_express.default.json({ limit: "50mb" }));
function getGenAIClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is not set in Secrets");
  }
  return new import_genai.GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build"
      }
    }
  });
}
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", name: "AI Sublimation Studio Pro Server" });
});
app.post("/api/gemini/generate-image", async (req, res) => {
  try {
    const { prompt, negativePrompt, model = "gemini-3.1-flash-image", aspectRatio = "1:1", guidanceScale = 7.5 } = req.body;
    const ai = getGenAIClient();
    const fullPrompt = `${prompt} ${negativePrompt ? `(Avoid: ${negativePrompt})` : ""} - high quality sublimation print design, crisp vectors, vibrant sublimation dyes, 300 dpi graphic art, ultra sharp detail`;
    const selectedModel = model.includes("flash-image") || model.includes("pro-image") ? model : "gemini-3.1-flash-image";
    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: {
        parts: [{ text: fullPrompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio || "1:1",
          imageSize: "1K"
        }
      }
    });
    let imageUrl = "";
    let responseText = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64Str = part.inlineData.data;
          const mime = part.inlineData.mimeType || "image/png";
          imageUrl = `data:${mime};base64,${base64Str}`;
        } else if (part.text) {
          responseText += part.text;
        }
      }
    }
    if (!imageUrl) {
      return res.status(500).json({ error: "No image was generated by Gemini model.", text: responseText });
    }
    res.json({ imageUrl, text: responseText });
  } catch (error) {
    console.error("Error generating AI sublimation image:", error);
    res.status(500).json({ error: error.message || "Failed to generate image" });
  }
});
app.post("/api/gemini/edit-image", async (req, res) => {
  try {
    const { imageBase64, mimeType = "image/png", prompt, action } = req.body;
    const ai = getGenAIClient();
    let editPrompt = prompt || "";
    if (action === "remove_bg") {
      editPrompt = "Isolate the main subject and make the background pure solid white transparent for sublimation printing.";
    } else if (action === "vectorize") {
      editPrompt = "Convert this graphic into ultra clean flat vector artwork style with sharp lines and high contrast colors for sublimation vinyl graphic.";
    } else if (action === "upscale") {
      editPrompt = "Enhance sharpness, remove compression artifacts, upscale resolution to 300 DPI print quality crisp detail.";
    }
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, "");
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image",
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType
            }
          },
          {
            text: editPrompt
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      }
    });
    let imageUrl = "";
    let responseText = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64Str = part.inlineData.data;
          const mime = part.inlineData.mimeType || "image/png";
          imageUrl = `data:${mime};base64,${base64Str}`;
        } else if (part.text) {
          responseText += part.text;
        }
      }
    }
    if (!imageUrl) {
      return res.status(500).json({ error: "No edited image returned.", text: responseText });
    }
    res.json({ imageUrl, text: responseText });
  } catch (error) {
    console.error("Error editing image via Gemini:", error);
    res.status(500).json({ error: error.message || "Failed to edit image" });
  }
});
app.post("/api/gemini/assist-prompt", async (req, res) => {
  try {
    const { idea, productType = "Caneca" } = req.body;
    const ai = getGenAIClient();
    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `You are an expert master designer in Sublimation Printing & Graphic Design. The user wants a sublimation print idea: "${idea}" for a product type: "${productType}".
Provide 3 professional prompts for AI image generation, optimized for vivid sublimation inks, high resolution, seamless borders or clean cutout graphics. Respond in JSON format with array of objects containing 'title', 'prompt', and 'negativePrompt'.`,
      config: {
        responseMimeType: "application/json"
      }
    });
    res.json({ result: response.text });
  } catch (error) {
    console.error("Error assisting prompt:", error);
    res.status(500).json({ error: error.message || "Failed to generate prompt recommendations" });
  }
});
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa"
    });
    app.use(vite.middlewares);
  } else {
    const distPath = import_path.default.join(process.cwd(), "dist");
    app.use(import_express.default.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(import_path.default.join(distPath, "index.html"));
    });
  }
  app.listen(PORT, "0.0.0.0", () => {
    console.log(`AI Sublimation Studio Pro running on http://localhost:${PORT}`);
  });
}
startServer();
//# sourceMappingURL=server.cjs.map
