import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '50mb' }));

// Helper to initialize GoogleGenAI with proper User-Agent
function getGenAIClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set in Secrets');
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

// API Health
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', name: 'AI Sublimation Studio Pro Server' });
});

// AI Sublimation Image Generation Endpoint
app.post('/api/gemini/generate-image', async (req, res) => {
  try {
    const { prompt, negativePrompt, model = 'gemini-3.1-flash-image', aspectRatio = '1:1', guidanceScale = 7.5 } = req.body;
    
    const ai = getGenAIClient();
    
    const fullPrompt = `${prompt} ${negativePrompt ? `(Avoid: ${negativePrompt})` : ''} - high quality sublimation print design, crisp vectors, vibrant sublimation dyes, 300 dpi graphic art, ultra sharp detail`;
    
    // Choose model based on request
    const selectedModel = model.includes('flash-image') || model.includes('pro-image') 
      ? model 
      : 'gemini-3.1-flash-image';

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: {
        parts: [{ text: fullPrompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: (aspectRatio as '1:1' | '3:4' | '4:3' | '9:16' | '16:9') || '1:1',
          imageSize: '1K',
        },
      },
    });

    let imageUrl = '';
    let responseText = '';

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64Str = part.inlineData.data;
          const mime = part.inlineData.mimeType || 'image/png';
          imageUrl = `data:${mime};base64,${base64Str}`;
        } else if (part.text) {
          responseText += part.text;
        }
      }
    }

    if (!imageUrl) {
      return res.status(500).json({ error: 'No image was generated by Gemini model.', text: responseText });
    }

    res.json({ imageUrl, text: responseText });
  } catch (error: any) {
    console.error('Error generating AI sublimation image:', error);
    res.status(500).json({ error: error.message || 'Failed to generate image' });
  }
});

// AI Generative Fill / Edit / Background Removal Endpoint
app.post('/api/gemini/edit-image', async (req, res) => {
  try {
    const { imageBase64, mimeType = 'image/png', prompt, action } = req.body;
    const ai = getGenAIClient();

    let editPrompt = prompt || '';
    if (action === 'remove_bg') {
      editPrompt = 'Isolate the main subject and make the background pure solid white transparent for sublimation printing.';
    } else if (action === 'vectorize') {
      editPrompt = 'Convert this graphic into ultra clean flat vector artwork style with sharp lines and high contrast colors for sublimation vinyl graphic.';
    } else if (action === 'upscale') {
      editPrompt = 'Enhance sharpness, remove compression artifacts, upscale resolution to 300 DPI print quality crisp detail.';
    }

    // Clean base64 string
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType,
            },
          },
          {
            text: editPrompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: '1:1',
          imageSize: '1K',
        },
      },
    });

    let imageUrl = '';
    let responseText = '';

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64Str = part.inlineData.data;
          const mime = part.inlineData.mimeType || 'image/png';
          imageUrl = `data:${mime};base64,${base64Str}`;
        } else if (part.text) {
          responseText += part.text;
        }
      }
    }

    if (!imageUrl) {
      return res.status(500).json({ error: 'No edited image returned.', text: responseText });
    }

    res.json({ imageUrl, text: responseText });
  } catch (error: any) {
    console.error('Error editing image via Gemini:', error);
    res.status(500).json({ error: error.message || 'Failed to edit image' });
  }
});

// AI Prompt Assistant / Pattern Prompt Optimizer
app.post('/api/gemini/assist-prompt', async (req, res) => {
  try {
    const { idea, productType = 'Caneca' } = req.body;
    const ai = getGenAIClient();

    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: `You are an expert master designer in Sublimation Printing & Graphic Design. The user wants a sublimation print idea: "${idea}" for a product type: "${productType}".
Provide 3 professional prompts for AI image generation, optimized for vivid sublimation inks, high resolution, seamless borders or clean cutout graphics. Respond in JSON format with array of objects containing 'title', 'prompt', and 'negativePrompt'.`,
      config: {
        responseMimeType: 'application/json',
      },
    });

    res.json({ result: response.text });
  } catch (error: any) {
    console.error('Error assisting prompt:', error);
    res.status(500).json({ error: error.message || 'Failed to generate prompt recommendations' });
  }
});

// Vite Middleware for development vs static serve for production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`AI Sublimation Studio Pro running on http://localhost:${PORT}`);
  });
}

startServer();
